### ISSUE TITLE
[Question] Rollup JSX transform with automatic runtime

### ISSUE THREAD

**Issue by jrson83** [piotr-cz/preact-rollup-react-jsx-transforms#1]
Yesterday I tried setting up a template for using Preact with Rollup and JSX transform with automatic runtime, so there is no need to `import { h } from 'preact'` in every component. I was not able to get it working but I found this repo. Thanks for creating this.

It seems [@rollup/plugin-babel](https://www.npmjs.com/package/@rollup/plugin-babel) and also [@rollup/plugin-sucrase](https://www.npmjs.com/package/@rollup/plugin-sucrase) have not yet integrated the usage of the automatic runtime?

Do you think the workaround you created is good to use for a production application, or did you create it for demonstration purpose only?
Maybe it is better to use Webpack which is seamless working with [@babel/plugin-transform-react-jsx](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx) and automatic runtime?

**Comment by piotr-cz** [comment]
Hi, this repo was created to reproduce issues with resthooks.io, as described here: https://github.com/coinbase/rest-hooks/issues/588.

Unfortunately it ended as too complex and decided to use [swr](https://swr.vercel.app/).

The tips in this repo may be useful for package authors but I wouldn't use them in a project itself.

Theres days I'm using [Vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project) with [preact-ts](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-preact-ts).
I works pretty well with jsx, try it out

**Comment by jrson83** [comment]
Thanks for the answer! Right, it seems very complex at the end. I will give Vite a try!
